// <auto-generated />
using EccomerceApi.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EccomerceApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EccomerceApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRoute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 200.0,
                            Description = "Description",
                            ImageRoute = "ee",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 300.0,
                            Description = "Description 2",
                            ImageRoute = "ee",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 400.0,
                            Description = "Description 3",
                            ImageRoute = "ee",
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 500.0,
                            Description = "Description 4",
                            ImageRoute = "ee",
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 600.0,
                            Description = "Description 5",
                            ImageRoute = "ee",
                            Name = "Product 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
